jwt:
  secret: aG51mfbYiVoX6hzSLfQQfCfsXuH5tTkvMwJM28u5p552f7ngBump1GWoXC5HPHoozyvJ9VzeYbRhLONC3jNcZa
  lifespan: 3600000

logging:
  level:
    '[org.springframework.security]': DEBUG

spring:
  application:
    name: MiniEcommercePlatform
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
